# Run checks (tests, linting, etc.) on push

name: CI
on:
  workflow_dispatch:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup node with module cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Cache Cypress installation
        uses: actions/cache@v3
        id: cache-cypress
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}

      - name: Dependency installation
        run: npm ci

  lint:
    runs-on: ubuntu-18.04
    needs: install
    steps:
      - uses: actions/checkout@v3

      - name: Setup node with module cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      # Install from cached .npm
      - name: Install cached modules
        run: npm ci

      # lint
      - name: Run linter
        run: npm run lint:verify

  test:
    runs-on: ubuntu-18.04
    needs: install
    steps:
      - uses: actions/checkout@v3

      - name: Setup node with module cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Cache Cypress installation
        uses: actions/cache@v3
        id: cache-cypress
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}

      - name: Install cached modules
        run: npm ci

      # run the test suite
      - name: Run unit tests
        run: npm test
        
      - name: Run integration tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          start: npm start